name: Add New Story

on:
  repository_dispatch:
    types: [add_story]

permissions:
  contents: write

jobs:
  update-story:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch current stories.json
        run: |
          curl -H "Authorization: Bearer ${{ secrets.STORY_UPLOAD_PAT }}" \
          -H "Accept: application/vnd.github.v3.raw" \
          -O https://raw.githubusercontent.com/${{ github.repository }}/main/stories.json

      - name: Add new story to stories.json
        run: |
          echo "Adding new story"
          cat stories.json
          STORY_JSON=$(jq '.stories += [{"title": "${{ github.event.client_payload.title }}", "date": "${{ github.event.client_payload.date }}", "content": "${{ github.event.client_payload.content }}"}]' stories.json)
          echo "${STORY_JSON}" > stories.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add stories.json
          git commit -m "Add new story: ${{ github.event.client_payload.title }}"
          git push origin main
